# List of tasks to run when running `upgrade-code doctor`
recipeEquivalences:
  i-lateral/silverstripe-commerce:
    - silvercommerce/silvercommerce-recipe
  i-lateral/silverstripe-orders:
    - silvercommerce/silvercommerce-recipe
  i-lateral/silverstripe-commerce-customisableproduct:
    - silvercommerce/silvercommerce-recipe
  i-lateral/silverstripe-commerce-bulkprice:
    - silvercommerce/silvercommerce-recipe
  silverstripe/silverstripe-omnipay:
    - silvercommerce/silvercommerce-recipe

